services:
  - type: web
    name: team-worklog-app
    runtime: node
    plan: free
    buildCommand: bash build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: RESET_ROOT_PASSWORD
        value: true
